### ISSUE TITLE
4.0.0-pre.1 has un declared passport-local dependency

### ISSUE THREAD

**Issue by rayfoss** [feathersjs-ecosystem/feathers-authentication-management#173]
# Description

I get the following log after installing 4.0.0-pre.1 with yarn on Node 16:

### Log:

```
Error: Cannot find module 'passport-local'
Require stack:
- /sandbox/node_modules/feathers-authentication-management/node_modules/@feathersjs/authentication-local/lib/index.js
- /sandbox/node_modules/feathers-authentication-management/dist/helpers/hash-password.js
- /sandbox/node_modules/feathers-authentication-management/dist/helpers/index.js
- /sandbox/node_modules/feathers-authentication-management/dist/methods/check-unique.js
- /sandbox/node_modules/feathers-authentication-management/dist/services/AuthenticationManagementService.js
- /sandbox/node_modules/feathers-authentication-management/dist/setupAuthManagement.js
- /sandbox/node_modules/feathers-authentication-management/dist/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/sandbox/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/sandbox/node_modules/feathers-authentication-management/node_modules/@feathersjs/authentication-local/lib/index.js:6:23)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .js] (/sandbox/node_modules/ts-node/src/index.ts:1361:43)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/sandbox/node_modules/feathers-authentication-management/dist/helpers/hash-password.js:40:30)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .js] (/sandbox/node_modules/ts-node/src/index.ts:1361:43)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/sandbox/node_modules/feathers-authentication-management/dist/helpers/index.js:24:23)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .js] (/sandbox/node_modules/ts-node/src/index.ts:1361:43)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/sandbox/node_modules/feathers-authentication-management/dist/methods/check-unique.js:43:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .js] (/sandbox/node_modules/ts-node/src/index.ts:1361:43)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/sandbox/node_modules/feathers-authentication-management/dist/services/AuthenticationManagementService.js:62:38)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .js] (/sandbox/node_modules/ts-node/src/index.ts:1361:43)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/sandbox/node_modules/feathers-authentication-management/dist/setupAuthManagement.js:7:41)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .js] (/sandbox/node_modules/ts-node/src/index.ts:1361:43)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/sandbox/node_modules/feathers-authentication-management/dist/index.js:17:45)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .js] (/sandbox/node_modules/ts-node/src/index.ts:1361:43)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:190:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async formattedImport (/home/sandbox/.nvm/versions/node/v16.12.0/lib/node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
    at async Object.exports.requireOrImport (/home/sandbox/.nvm/versions/node/v16.12.0/lib/node_modules/mocha/lib/nodejs/esm-utils.js:48:32)
    at async Object.exports.loadFilesAsync (/home/sandbox/.nvm/versions/node/v16.12.0/lib/node_modules/mocha/lib/nodejs/esm-utils.js:103:20)
    at async singleRun (/home/sandbox/.nvm/versions/node/v16.12.0/lib/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/home/sandbox/.nvm/versions/node/v16.12.0/lib/node_modules/mocha/lib/cli/run.js:374:5)
```

# Debugging

I've confirmed in node_modules [4.0.0-pre.1](https://github.com/feathersjs-ecosystem/feathers-authentication-management/tree/typescript) is being pulled... but somehow, the @feathersjs/authentication-local subdependency is version 1.2.9

**Comment by rayfoss** [comment]
Aaaaand I've learned yarn not only relies on flaky UV to function, doesn't run on all my devices, but also manages to corrupt node_modules on upgrades... GENIUS

**Comment by fratzinger** [comment]
`pnpm` for the win.
Please let me know, how it went with the pre version! :)
